### ISSUE TITLE
Question: how to use it?

### ISSUE THREAD

**Issue by stepancar** [longlho/ts-transform-img#3]
Hello! Thank you for example for customTransformers
Could you please share how you use it with your projects?
Could you provide Webpack, gulp, etc config?

**Comment by longlho** [comment]
The way I use it is using a wrapper similar to `compile.ts`. You can try using it with webpack using [ts-loader](https://github.com/TypeStrong/ts-loader#getcustomtransformers-----before-transformerfactory-after-transformerfactory---)
